POST /api/task HTTP/1.1
Host: localhost:3000
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNydXpyb3ZpcmFAZ21haWwuY29tIiwiaWQiOiI2NTAxZTM1Zjc3OTJmMGExMWE0NjdkOTEiLCJpYXQiOjE2OTQ3MDk3OTEsImV4cCI6MTY5NTMxNDU5MX0.UBQhT8cG-opHn-noPQ-f-UyRu9RYaIqwhfhqO1n3xYQ
{
"title":"create web web",
"completed":false,
"categoryId":"64eec253fd47ec2a97f13766",
"userId" :"64eec50efd47ec2a97f1376d"
}