PUT /api/task/id/64e62abe44ec3195dd7cf387 HTTP/1.1
Host: localhost:3000
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNydXpyb3ZpcmFAZ21haWwuY29tIiwiaWF0IjoxNjkzNTMyNzEwLCJleHAiOjE2OTQxMzc1MTB9.sRpPrmHrY8OnM4UhXHkB4T_zg0wJjIlYmyFiWJ4PQvw
{
  "title":"create api",
  "completed":false,
  "categoryId":"64e500447e721ef625fde2f2"
}